server:
  port: 9000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes: # 数组, 所以使用 -
        - id: product-service
          uri: lb://gateway-product
          predicates: # 断言, 满足这个断言条件, 就会映射到上面的目标URL
            - Path=/**
          filters:
            - PrefixPath=/product/get
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server1:7744/eureka/,http://eureka-server1:7745/eureka/
